seml:
  name: iclr21_collectivecertificate_smoothing
  db_collection: iclr21_collectivecertificate_smoothing
  executable: experiment_smoothing.py
  conda_environment: rgnn_at_scale
  project_root_dir: ../..
  output_dir: seml/smoothing/output

slurm:
  experiments_per_job: 1
  sbatch_options:
    gres: gpu:1       # num GPUs
    mem: 16G          # memory
    cpus-per-task: 4  # num cores
    time: 1-12:00     # max time, D-HH:MM

fixed:
  n_samples_pre_eval: 1000
  conf_alpha: 0.000003558718861 # 0.01 / 2810
  # conf_alpha: 0.05
  batch_size: 1
  artifact_dir: cache
  smoothing_result_storage_type: collectivesmoothing
  model_storage_type: collective
  device: 0

grid:
  dataset:
    type: choice
    options:
      - cora_ml_collective
      # - cora_ml
      # - citeseer

  seed:
    type: choice
    options:
      - 0
      - 1
      - 2
      - 3
      - 4

  sample_params:
    type: choice
    options:
    - pf_plus_adj:  0.0
      pf_minus_adj: 0.0
      pf_plus_att: 0.002
      pf_minus_att: 0.6
      n_samples: 1_000_000
    